### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by Mhamad-Raad** [Mhamad-Raad/Capstone-API#1]
# Review
## in the followings you have all the information that you need to review the project:
- Link: https://github.com/users/Mhamad-Raad/projects/4
## Number of participants: 3
- @Mhamad-Raad Student A
- @Solobarine Student B
- @rbreva Student C

**Comment by ha-manel** [comment]
# STATUS: REQUIRES CHANGES ♻️ 
## Hey team!

Good job on copying the project. However, you still have to copy the cards too, and assign the tasks to each other (group tasks should be assigned to all of you) 👍 

Best of luck 😄

**Comment by rloterh** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a broken Github link provided. Kindly ensure to provide the correct link and resubmit for another review.

![image](https://user-images.githubusercontent.com/12745474/196290864-99b68a08-4157-4f67-8c48-0b6bb4cb3782.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by KayLemba** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello  @TEAM   , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 




Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
